# Generated by Django 6.0 on 2026-02-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Новое'), (2, 'В обработке'), (3, 'Закрыто')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.telegramuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
